import java.io.*;
import java.util.HashMap;

public class Prob5{
	static String eFile;
	static String fFile;
	static String tFile;
	static PrintStream stdout = System.out;

	/*
	* generates keys for a table of q's, t's, or counts
	*/
	public static String makeKey(String ... args){
		String key = "";
		for(int i = 0; i < args.length; i++){
			key += (i + 1 == args.length) ? args[i] : args[i] + "_";
		}
		return key;
	}

	/*
	* gets initial t values from a file generated by Prob4
	*/
	public static HashMap<String, Double> getTs() throws IOException{
		BufferedReader tReader = new BufferedReader(new FileReader(tFile));
		HashMap<String, Double> params = new HashMap();
		String line;
		while((line = tReader.readLine()) != null){
			String[] pair = line.split("~");
			params.put(pair[0], Double.parseDouble(pair[1]));
		}

		return params;
	}

	public static void increment(HashMap<String, Double> counts, double by, String key){
		if(counts.containsKey(key))
			counts.put(key, counts.get(key) + by);
		else
			counts.put(key, by);
	}
	
	public static double[][][][] emAlg(int iterations) throws IOException{
		double[][][][] qParams = new double[40][40][40][40];
		HashMap<String, Double> tParams = getTs();
		double[][][][] qCounts = new double[40][40][40][41];
		HashMap<String, HashMap<String, Double>> tCounts = new HashMap();

		for(int its = 1; its <= iterations; its++){
			//reset all stored counts to 0
			BufferedReader eReader = new BufferedReader(new FileReader(eFile));
			BufferedReader fReader = new BufferedReader(new FileReader(fFile));
			String eline, fline;
			int k = 1;
			while((eline = eReader.readLine()) != null){
				if(k % 500 == 0)
					stdout.println("on line "+k);
				String[] eWords = eline.split(" ");
				String[] fWords = fReader.readLine().split(" ");//assumes corpora are equally long
				int l = eWords.length;
				int m = fWords.length;
				for(int i = 0; i < fWords.length; i++){
					//calculate denominator for delta
					double denom = 0;
					for(int j = 0; j < eWords.length; j++){
						//String qKey = makeKey(""+j,""+i,""+eWords.length,""+fWords.length);
						String tKey = makeKey(fWords[i],eWords[j]);
						if(qParams[j][i][l][m] == 0)
							qParams[j][i][l][m] = 1.0 / (eWords.length + 1);
						denom += qParams[j][i][l][m] * tParams.get(tKey);//assumes this t param has been calculated in Prob4
					}/*
					for(int j = 0; j < eWords.length; j++){
						String qKey = makeKey(""+j,""+i,""+eWords.length,""+fWords.length);
						String tKey = makeKey(fWords[i],eWords[j]);
						//calculate delta
						double delta = (denom > 0) ? tParams.get(qKey) * tParams.get(tKey) / denom : 0;
						//increment counts by delta
						String c1 = makeKey(fWords[i],eWords[j]);
						increment(counts,delta,c1);
						increment(counts,delta,eWords[j]);
						String c3 = makeKey(""+j,""+i,""+eWords.length,""+fWords.length);
						increment(counts,delta, c3);
						String c4 = makeKey(""+i,""+eWords.length,""+fWords.length);
						increment(counts,delta,c4);
						//update q and t
						tAndq.put(qKey, counts.get(c3) / counts.get(c4));
						tAndq.put(tKey, counts.get(c1) / counts.get(eWords[j]));
					}*/
				}
				k++;
			}
		}
		//finally...
		return qParams;
	}

	public static void main(String[] args) throws IOException{
		if(args.length != 3){
			stdout.println("usage: java Prob5 <english_corpus> <foreign_corpus> <tParams_file>");
			return;
		}

		eFile = args[0];
		fFile = args[1];
		tFile = args[2];
		emAlg(1);
		/*int i = 0;
		HashMap<String, Double> params = emAlg(1);
		for(String k : params.keySet()){
			if(i >= 10)
				break;
			stdout.println(k+": "+params.get(k));
			i++;
		}*/
	}
}